Update patch set 4
Patch Set 4:

Tried to make a call without a sim card on aosp_sailfish-userdebug, got:
07-12 04:32:23.209  3602  3602 E AndroidRuntime: FATAL EXCEPTION: main
07-12 04:32:23.209  3602  3602 E AndroidRuntime: Process: com.android.dialer, PID: 3602
07-12 04:32:23.209  3602  3602 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/dialer/enrichedcall/EnrichedCallManager$Filter;
07-12 04:32:23.209  3602  3602 E AndroidRuntime: 	at com.android.dialer.enrichedcall.stub.StubEnrichedCallModule.provideEnrichedCallManager(StubEnrichedCallModule.java:36)
07-12 04:32:23.209  3602  3602 E AndroidRuntime: 	at com.android.dialer.enrichedcall.stub.StubEnrichedCallModule_ProvideEnrichedCallManagerFactory.get(StubEnrichedCallModule_ProvideEnrichedCallManagerFactory.java:19)
07-12 04:32:23.209  3602  3602 E AndroidRuntime: 	at com.android.dialer.enrichedcall.stub.StubEnrichedCallModule_ProvideEnrichedCallManagerFactory.get(StubEnrichedCallModule_ProvideEnrichedCallManagerFactory.java:8)
07-12 04:32:23.209  3602  3602 E AndroidRuntime: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
07-12 04:32:23.209  3602  3602 E AndroidRuntime: 	at com.android.dialer.binary.aosp.DaggerAospDialerRootComponent$EnrichedCallComponentImpl.getEnrichedCallManager(DaggerAospDialerRootComponent.java:1234)
07-12 04:32:23.209  3602  3602 E AndroidRuntime: 	at com.android.dialer.searchfragment.list.NewSearchFragment.onResume(NewSearchFragment.java:463)
07-12 04:32:23.209  3602  3602 E AndroidRuntime: 	at android.app.Fragment.performResume(Fragment.java:2554)
07-12 04:32:23.209  3602  3602 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1322)
07-12 04:32:23.209  3602  3602 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1557)
07-12 04:32:23.209  3602  3602 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1618)
07-12 04:32:23.209  3602  3602 E AndroidRuntime: 	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2196)
07-12 04:32:23.209  3602  3602 E AndroidRuntime: 	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2142)
07-12 04:32:23.209  3602  3602 E AndroidRuntime: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2043)
07-12 04:32:23.209  3602  3602 E AndroidRuntime: 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:719)
07-12 04:32:23.209  3602  3602 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
07-12 04:32:23.209  3602  3602 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-12 04:32:23.209  3602  3602 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
07-12 04:32:23.209  3602  3602 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6518)
07-12 04:32:23.209  3602  3602 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-12 04:32:23.209  3602  3602 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-12 04:32:23.209  3602  3602 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:853)
07-12 04:32:23.209  3602  3602 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.dialer.enrichedcall.EnrichedCallManager$Filter" on path: DexPathList[[zip file "/system/priv-app/Dialer/Dialer.apk"],nativeLibraryDirectories=[/system/priv-app/Dialer/lib/arm64, /system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]
07-12 04:32:23.209  3602  3602 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
07-12 04:32:23.209  3602  3602 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
07-12 04:32:23.209  3602  3602 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-12 04:32:23.209  3602  3602 E AndroidRuntime: 	... 21 more

Patch-set: 4
Reviewer: Gerrit User 1002751 <1002751@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0